### ISSUE TITLE
Porting website from distill to quarto

### ISSUE THREAD

**Issue by samanthacsik** [samanthacsik/samanthacsik.github.io#4]
### General steps: 
1. created new repo, [samanthacsik-quarto-website](https://github.com/samanthacsik/samanthacsik-quarto-website) that I'll eventually rename as **samanthacsik.github.io** once I decommission my distill site
2. followed steps as outlined in the [Create the scaffolding for your website](https://ucsb-meds.github.io/creating-quarto-websites/#create-the-scaffolding-for-your-website) section (I just went with the RStudio setup option)
3. created `.qmd` file for my **resources** page, copied content over from `.Rmd` file and linked to navbar in `_quarto.yml`
4. added blog following the steps outlined in #2 

---
### Misc.
* install [font awesome extension](https://github.com/quarto-ext/fontawesome) using the following in the command line:
`quarto install extension quarto-ext/fontawesome`
 
---
### Code chunks
* update code chunk options = moving them from inside `{}` to hashpipes, `#|`; quarto uses `-` rather than `_` as a separator and booleans are lowercase (e.g. `true`, `false`) rather than uppercase (e.g. `TRUE`, `FALSE`)

---
### Blog post yaml differences:
* note differences in author name, orcid, affiliation-url

Quarto: 
```
title: title here
author:
   - name: Samantha Csik
   - orcid: ####-####-####-####
   - affiliation: Master of Environmental Data Science & the National Center for Ecological Analysis & Synthesis
   -  affiliation_url: https://bren.ucsb.edu/masters-programs/master-environmental-data-science
```

versus distill:

```
title: title here
author: 
   - first_name: "Samantha"
   - last_name: "Csik"
   - orcid_id: ####-####-####-####
   - affiliation: Master of Environmental Data Science & the National Center for Ecological Analysis & Synthesis
   - affiliation_url: https://bren.ucsb.edu/masters-programs/master-environmental-data-science
```

* Quarto categories inside brackets (`[cat1, cat2]`) while distill is listed:
```
category:
    - cat1
    - cat 2
```
 
* Quarto preview image option: `image: preview_image.png` vs. distill option: `preview: preview_image.png`

* adding citation links:
```
citation: 
  url: https://samanthacsik.github.io/talks/2022-08-05-creating-your-personal-website-using-quarto/
```

---
### Deploying

There may be a more sophisticated way of doing this, but these were the steps I took:

1. My distill site was hosted for free via GitHub pages from the repo `samanthacsik.github.io` -- I first needed to free the domain name by unpublishing the distill website. To do this, go to Settings > Pages > click the three dots next to Visit Site > Unpublish site

<img width="999" alt="Screen Shot 2022-09-04 at 1 49 21 PM" src="https://user-images.githubusercontent.com/43836046/188333023-8d724af0-0083-4438-a579-6856ac9b49f2.png">

2. Rename the original website repo something different (bc we'll need to rename the quarto website repo as `samanthacsik.github.io`. I renamed mine to [samanthacsik-distill-site](https://github.com/samanthacsik/samanthacsik-distill-site) by going to Settings > General > Rename site (type new name in the box at the top of the page)
<img width="1379" alt="Screen Shot 2022-09-04 at 1 51 21 PM" src="https://user-images.githubusercontent.com/43836046/188332997-019c85a0-82c1-4590-b578-3f9187c508b0.png">

3. Go to the repo containing your quarto website and rename as `samanthacsik.github.io`.
4. Go to Settings > Pages and deploy (make sure it's deploying from `/docs` and not `/root`
